In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
customers = pd.read_csv('Mall_Customers_Cluster.csv')

In [3]:
customers

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  \
0             1       1   19                  15                      39   
1             2       1   21                  15                      81   
2             3       0   20                  16                       6   
3             4       0   23                  16                      77   
4             5       0   31                  17                      40   
5             6       0   22                  17                      76   
6             7       0   35                  18                       6   
7             8       0   23                  18                      94   
8             9       1   64                  19                       3   
9            10       0   30                  19                      72   
10           11       1   67                  19                      14   
11           12       0   35                  19                      99   
12           13       0   58                  20                      15   
13           14       0   24                  20                      77   
14           15       1   37                  20                      13   
15           16       1   22                  20                      79   
16           17       0   35                  21                      35   
17           18       1   20                  21                      66   
18           19       1   52                  23                      29   
19           20       0   35                  23                      98   
20           21       1   35                  24                      35   
21           22       1   25                  24                      73   
22           23       0   46                  25                       5   
23           24       1   31                  25                      73   
24           25       0   54                  28                      14   
25           26       1   29                  28                      82   
26           27       0   45                  28                      32   
27           28       1   35                  28                      61   
28           29       0   40                  29                      31   
29           30       0   23                  29                      87   
..          ...     ...  ...                 ...                     ...   
170         171       1   40                  87                      13   
171         172       1   28                  87                      75   
172         173       1   36                  87                      10   
173         174       1   36                  87                      92   
174         175       0   52                  88                      13   
175         176       0   30                  88                      86   
176         177       1   58                  88                      15   
177         178       1   27                  88                      69   
178         179       1   59                  93                      14   
179         180       1   35                  93                      90   
180         181       0   37                  97                      32   
181         182       0   32                  97                      86   
182         183       1   46                  98                      15   
183         184       0   29                  98                      88   
184         185       0   41                  99                      39   
185         186       1   30                  99                      97   
186         187       0   54                 101                      24   
187         188       1   28                 101                      68   
188         189       0   41                 103                      17   
189         190       0   36                 103                      85   
190         191       0   34                 103     

In [19]:
data = pd.DataFrame(customers)
target = data['Cluster'].values
target

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 4, 2, 1, 2, 2, 2, 1, 2, 2, 2,
       4, 2, 4, 2, 4, 2, 2, 2, 1, 2, 1, 2, 4, 2, 4, 2, 2, 2, 4, 2, 1, 2,
       4, 2, 4, 2, 2, 2, 4, 2, 2, 1, 4, 1, 4, 1, 2, 1, 1, 2, 4, 4, 1, 2,
       4, 4, 2, 2, 1, 4, 4, 4, 1, 2, 4, 1, 2, 4, 1, 1, 1, 4, 2, 1, 4, 2,
       2, 4, 4, 2, 1, 4, 2, 2, 4, 2, 1, 2, 2, 4, 1, 0, 1, 2, 4, 1, 1, 1,
       1, 2, 3, 0, 2, 2, 4, 4, 4, 4, 0, 3, 0, 0, 3, 0, 3, 0, 1, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 4, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0])

In [20]:
train = data[['Age', 'Gender', 'Annual Income (k$)', 'Spending Score (1-100)']].values
train

array([[ 19,   1,  15,  39],
       [ 21,   1,  15,  81],
       [ 20,   0,  16,   6],
       [ 23,   0,  16,  77],
       [ 31,   0,  17,  40],
       [ 22,   0,  17,  76],
       [ 35,   0,  18,   6],
       [ 23,   0,  18,  94],
       [ 64,   1,  19,   3],
       [ 30,   0,  19,  72],
       [ 67,   1,  19,  14],
       [ 35,   0,  19,  99],
       [ 58,   0,  20,  15],
       [ 24,   0,  20,  77],
       [ 37,   1,  20,  13],
       [ 22,   1,  20,  79],
       [ 35,   0,  21,  35],
       [ 20,   1,  21,  66],
       [ 52,   1,  23,  29],
       [ 35,   0,  23,  98],
       [ 35,   1,  24,  35],
       [ 25,   1,  24,  73],
       [ 46,   0,  25,   5],
       [ 31,   1,  25,  73],
       [ 54,   0,  28,  14],
       [ 29,   1,  28,  82],
       [ 45,   0,  28,  32],
       [ 35,   1,  28,  61],
       [ 40,   0,  29,  31],
       [ 23,   0,  29,  87],
       [ 60,   1,  30,   4],
       [ 21,   0,  30,  73],
       [ 53,   1,  33,   4],
       [ 18,   1,  33,  92],
       [ 49,  

In [21]:
X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.3, random_state=1) # 70% training and 30% test

In [22]:
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=10)

print(X_test)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

[[ 27   0  46  51]
 [ 65   0  38  35]
 [ 49   0  33  14]
 [ 67   1  62  59]
 [ 41   0  99  39]
 [ 32   1 137  18]
 [ 24   1  60  52]
 [ 31   0  17  40]
 [ 23   0  29  87]
 [ 36   0  87  27]
 [ 28   1  87  75]
 [ 52   1  23  29]
 [ 35   0  19  99]
 [ 50   0  58  46]
 [ 65   1  63  52]
 [ 51   0  67  43]
 [ 30   0  78  73]
 [ 21   0  33  81]
 [ 44   0  73   7]
 [ 53   1  46  46]
 [ 33   1  42  60]
 [ 35   0  21  35]
 [ 49   0  39  28]
 [ 32   0  60  42]
 [ 21   0  30  73]
 [ 19   1  81   5]
 [ 36   0  37  26]
 [ 40   0  29  31]
 [ 38   0 113  91]
 [ 35   1  28  61]
 [ 27   0  40  47]
 [ 36   0  85  75]
 [ 47   0 120  16]
 [ 27   1  88  69]
 [ 58   1  88  15]
 [ 27   0  60  50]
 [ 52   0  88  13]
 [ 60   0  50  56]
 [ 32   0  48  47]
 [ 36   1  87  10]
 [ 68   1  63  43]
 [ 54   1  63  46]
 [ 36   0 103  85]
 [ 37   1  20  13]
 [ 51   0  44  50]
 [ 35   0  23  98]
 [ 18   0  65  48]
 [ 20   0  37  75]
 [ 30   1  99  97]
 [ 23   0  70  29]
 [ 48   1  61  42]
 [ 39   1  69  91]
 [ 50   0  6

In [23]:
from sklearn import metrics
print("Accuracy (k=10):",metrics.accuracy_score(y_test, y_pred))

Accuracy (k=10): 0.8333333333333334


In [24]:
# save the model to disk using Pickle
import pickle
filename = 'knn_model.obj'
pickle.dump(knn, open(filename, 'wb'))

In [25]:
filename = 'knn_model.obj'
knn_model = pickle.load(open(filename, 'rb'))
knn_model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [26]:
predict = knn_model.predict(X_train)

In [27]:
X_train

array([[ 63,   0,  65,  43],
       [ 68,   0,  48,  48],
       [ 23,   0,  54,  52],
       [ 48,   1,  39,  36],
       [ 20,   1,  21,  66],
       [ 22,   0,  17,  76],
       [ 40,   1,  71,  95],
       [ 21,   0,  62,  42],
       [ 29,   0,  40,  42],
       [ 43,   0,  48,  50],
       [ 50,   0,  43,  45],
       [ 21,   0,  54,  57],
       [ 29,   0,  98,  88],
       [ 34,   1,  78,   1],
       [ 42,   1,  86,  20],
       [ 19,   1,  64,  46],
       [ 58,   0,  20,  15],
       [ 49,   0,  65,  59],
       [ 40,   0,  60,  40],
       [ 27,   1,  67,  56],
       [ 47,   0,  78,  16],
       [ 68,   0,  59,  55],
       [ 38,   1,  54,  55],
       [ 40,   0,  69,  58],
       [ 32,   0, 103,  69],
       [ 24,   0,  20,  77],
       [ 67,   1,  54,  41],
       [ 25,   0,  72,  34],
       [ 28,   1, 101,  68],
       [ 24,   0,  39,  65],
       [ 20,   1,  61,  49],
       [ 42,   0,  34,  17],
       [ 29,   0,  79,  83],
       [ 54,   0, 101,  24],
       [ 38,  